name: Deploy to Intra Server via Local PC

on:
  push:
    branches: [ main ] # mainブランチにpushされたら実行

jobs:
  deploy:
    # ローカルPCのランナーで実行するという指定
    runs-on: self-hosted

    steps:
      - name: Checkout code
        run: git config --global http.sslVerify false
        shell: cmd
      - uses: actions/checkout@v4

      - name: Deploy files via SCP
        shell: powershell
        # scpコマンドを使って、ローカルPCに落ちてきたコードを社内サーバーへ転送する
        run: |
          # ↓秘密鍵のパスは、あなたのローカルPCの実際のユーザー名に合わせて書き換えてください
          $PrivateKeyPath = `C:\gs_intra_new_key\github_deploy_key`
          $TargetServer = `Administrator@192.168.8.205:C:\inetpub\gs_intra`
          
          # -o StrictHostKeyChecking=no は、初回接続時の yes/no 確認をスキップするオプションです
          scp -v -B -i $PrivateKeyPath -o StrictHostKeyChecking=no -r .\* $TargetServer